spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #username: postgres
    username: login_registration_user
    #password: 1024
    password: 91gcmYA55C6jRy5MCyXh4f03y3F3vJSp
    #url: jdbc:postgresql://localhost:5432/login_registration
    url: jdbc:postgresql://dpg-cihtkr5ph6erq6kmgdag-a:5432/login_registration

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true
    show-sql: true
#  mail:
#    host: localhost
#    port: 1025
#    username: hello
#    password: hello
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
#server:
#  port: 1010
