spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1024
    url: jdbc:postgresql://localhost:5432/login_registration

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true
    show-sql: true
server:
  port: 1010
